select * from customer limit 20

--Q1. what is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as total_revenue from customer

--Q2. which customer used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating" from customer
group by item_purchased
order by avg(review_rating) desc limit 5 

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average 
--    spend and total revenue between subscribers and non-subscribers

select subscription_status,
count(customer_id) as total_cuatomers,
round(avg(purchase_amount),2) as "Average spend", 
round(sum(purchase_amount),2) as "total revenue" ,
round(SUM(purchase_amount) * 100.0 / 
(SELECT SUM(purchase_amount) FROM customer), 2) 
AS percentage_of_total
from customer
group by subscription_status
order by "total revenue","Average spend" desc

--Q6. which 5 products have the highest percentage of the 
--    purchase with discounts applied?

select item_purchased,
round(
count(case when discount_applied = 'Yes' then 1 end)*100.0/count(*),2) as "Discount percentage"
from customer
group by item_purchased
order by "Discount percentage" desc limit 5

--Q7. Segment customer into New, Returning, and Loyal based
--    on their toatal number of previous purchases, and show the count of each segment.

select 
   case 
   when previous_purchases = 1 then 'New'
   when previous_purchases <= 10 then 'Returning'
   else 'Loyal'
   end
   as "Customer tag",
   count(*) as "number of customers"
from customer
group by "Customer tag"
order by "number of customers"
     --    or  
	 
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as "Customer Segment"
from customer
)

select "Customer Segment" , count(*) as "Number of Customers"
from customer_type
group by "Customer Segment"
order by "Number of Customers"

--Q8. what are the top 3 most purchased products within each category?

select rank_number,category, item_purchased,
purchase_count
from
(
	select category, item_purchased, count(*) as purchase_count,
		row_number() over (partition by category order by count(*) desc)
		as rank_number
	from customer
	group by category , item_purchased
)
where rank_number <= 3

-- or 

with item_count as
(
	select category, item_purchased, count(customer_id) as total_orders,
		row_number() over (partition by category order by count(customer_id) desc)
		as rank_number
	from customer
	group by category, item_purchased 
)

select rank_number, category, item_purchased, total_orders
from item_count
where rank_number <= 3

--Q9. Are customer who are repeat buyers
-- (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id)
from customer
where previous_purchases > 5
group by subscription_status

--Q10. what is the revenue contribution of each age group?

select age_group,sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;





